pub const config_asset_name = "parameters"

pub const max_oracle_validity_range = 3600000

pub const assetname_identifier_charlie = "OracleFeed"

pub const charlie_identifier_asset_name = "OracleFeed"

pub const orcfax_identifier_pointer_asset_name = #"000de140"

//feed is empty
pub const orcfax_identifier_feed_asset_name = ""

//7 hours max time hearbeat
pub const max_orcfax_tolerance = 25200000

pub const min_ada_spendable = 300000
